monitor=,preferred,auto,1

exec-once = swaybg -i ~/.config/wallpapers/wallpaper.png -m fill
exec-once=sleep 1 && waybar > /dev/null 2>&1
exec-once=pipewire
exec-once=swww-daemon
exec-once=mako
exec-once =sleep 2 && waybar -c ~/.config/waybar-dock/config.jsonc -s ~/.config/waybar-dock/style.css > /dev/null 2>&1
exec-once = eww open clock-window
exec-once = eww open sysmon-window
exec-once = eww open quote-window

input {
    kb_layout = us
    touchpad {
	natural_scroll = true
    }
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(7aa2f733) rgba(bb9af733) 45deg
    col.inactive_border = rgba(1a1b2eff)
    layout = dwindle
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 0.92
    shadow {
	enabled = true
	range = 15
	render_power = 3
	color = rgba(7aa2f733)
   }
   blur {
	enabled = true
	size = 5
	passes = 2
	new_optimizations = true
  }
}

animations {
    enabled = true

    bezier = bounce, 0.05, 0.9, 0.1, 1.08
    bezier = smooth, 0.4, 0.0, 0.2, 1.0
    bezier = overshot, 0.13, 0.99, 0.29, 1.1
    bezier = snappy, 0.68, -0.55, 0.27, 1.55

    animation = windows, 1, 6, bounce, slide
    animation = windowsIn, 1, 5, overshot, popin 60%
    animation = windowsOut, 1, 4, smooth, popin 80%
    animation = windowsMove, 1, 4, snappy
    animation = fade, 1, 5, smooth
    animation = fadeIn, 1, 4, smooth
    animation = fadeOut, 1, 4, smooth
    animation = workspaces, 1, 5, overshot, slidevert
    animation = specialWorkspace, 1, 5, smooth, fade
}

$terminal = kitty
$menu = rofi -show drun -show-icons -theme ~/.config/rofi/tokyo-night.rasi

bind = SUPER, Return, exec, $terminal
bind = SUPER, R, exec, $menu
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, P, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER, E, exec, thunar
bind = SUPER SHIFT, Space, togglefloating
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
bind = SUPER, D, exec, nwg-drawer
bind = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
